---
- tasks:
  - name: Abort if the host is not an arch install
    fail:
      msg: "This host is not booted from the Arch install media!"
    when: ansible_nodename != 'archiso'
    tags:
      - quick_exit